@startuml
start
:生成ExportBootstrap;
:传入参数,调用initRequest方法初始化ExportRequest;
:传入参数,调用initPipeline初始化pipeline;
:传入参数,调用build生成对应的ExportService;
:调用exportFile方法;
:按顺序执行pipeline的所有handler.handlerRequest;
:执行若干handler;
:DefaultExcelExportHandler;
:返回exportResponse;
end
@enduml